name: Camden Bickel
description: blogging, occasionally.
meta_description: "occasional posts about anything"

aboutPage: true

markdown: redcarpet
redcarpet:
	extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
highlighter: pygments

paginate: 20
baseurl: /blog/
domain_name: 'http://camdenb.github.io/blog/'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://camdenb.github.io/blog/'
author:         'camden'
authorTwitter:  'bearchinski'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
